# Generated by Django 6.0.6 on 2026-07-13 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=24)),
                ('card_summary', models.CharField(blank=True, max_length=60)),
                ('detail_intro', models.TextField(blank=True)),
                ('core_activity', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('deliverable_name', models.CharField(blank=True, max_length=100)),
                ('is_experiential', models.BooleanField(default=False)),
                ('previous_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_lessons', to='curriculums.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=30, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('result_label', models.CharField(max_length=20)),
                ('question_text', models.CharField(max_length=32)),
                ('help_text', models.CharField(blank=True, max_length=52)),
                ('input_type', models.CharField(default='long_text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=80)),
                ('required', models.BooleanField(default=True)),
                ('min_length', models.PositiveIntegerField(default=0)),
                ('max_length', models.PositiveIntegerField(default=100)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curriculums.lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=50)),
                ('lesson_badge', models.CharField(blank=True, max_length=20)),
                ('lesson_intro', models.TextField(blank=True)),
                ('deliverable_label', models.CharField(blank=True, max_length=50)),
                ('usage_label', models.CharField(blank=True, max_length=100)),
                ('detail_cta', models.CharField(blank=True, max_length=18)),
                ('autosave_text', models.CharField(blank=True, max_length=50)),
                ('complete_title', models.CharField(blank=True, max_length=50)),
                ('complete_subtitle', models.CharField(blank=True, max_length=100)),
                ('result_section_title', models.CharField(blank=True, max_length=50)),
                ('insight_title', models.CharField(blank=True, max_length=50)),
                ('insight_body', models.TextField(blank=True)),
                ('use_case_text', models.TextField(blank=True)),
                ('reflection_title', models.CharField(blank=True, max_length=20)),
                ('reflection_help', models.CharField(blank=True, max_length=100)),
                ('reflection_placeholder', models.CharField(blank=True, max_length=100)),
                ('reflection_max_length', models.PositiveIntegerField(default=50)),
                ('next_cta', models.CharField(blank=True, max_length=18)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen', to='curriculums.lesson')),
                ('next_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_next_refs', to='curriculums.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=16)),
                ('summary', models.CharField(blank=True, max_length=65)),
                ('lesson_count', models.PositiveIntegerField(default=0)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('deliverable_name', models.CharField(blank=True, max_length=22)),
                ('unlock_rule', models.CharField(blank=True, max_length=50)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='search.major')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('major', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('material_type', models.CharField(choices=[('lecture', '강의'), ('article', '아티클'), ('practice', '실습'), ('program', '프로그램')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('duration_text', models.CharField(blank=True, max_length=30)),
                ('price_type', models.CharField(choices=[('free', '무료'), ('paid', '유료')], default='free', max_length=10)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('thumbnail_asset_key', models.CharField(blank=True, max_length=100)),
                ('recommendation_reason', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('last_checked_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('lessons', models.ManyToManyField(blank=True, related_name='materials', to='curriculums.lesson')),
                ('majors', models.ManyToManyField(blank=True, related_name='materials', to='search.major')),
                ('stages', models.ManyToManyField(blank=True, related_name='materials', to='curriculums.stage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculums.stage'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', '잠김'), ('available', '진행 예정'), ('in_progress', '진행중'), ('completed', '완료')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculums.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='LessonAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='curriculums.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='curriculums.lessonquestion')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='LessonReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection_text', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='curriculums.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='curriculums.material')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'material')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('stage', 'order')},
        ),
    ]
