# Generated by Django 6.0.6 on 2026-07-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='material',
            name='majors',
        ),
        migrations.RemoveField(
            model_name='material',
            name='stages',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
