# Generated by Django 6.0.6 on 2026-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_scope',
            field=models.CharField(choices=[('major', '전공 게시판'), ('all', '전체 게시판')], default='major', max_length=10),
        ),
    ]
