# Generated by Django 6.0.6 on 2026-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_board_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('question', '질문'), ('info', '정보 공유')], max_length=10, null=True),
        ),
    ]
