# Generated by Django 6.0.6 on 2026-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='detailGuide',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='introGuide',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='major',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
