# Generated by Django 6.0.6 on 2026-07-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_choice_reason_remove_experience_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='detailGuide',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='introGuide',
        ),
        migrations.AddField(
            model_name='experience',
            name='introText',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='taskSummary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='experiencequestion',
            name='helpText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experiencequestion',
            name='placeholder',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
