# Generated by Django 6.0.6 on 2026-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_experience_detailguide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='deliverable_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_min',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
