# Generated by Django 6.0.6 on 2026-07-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_experience_deliverable_name_experience_duration_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='deliverable_name',
            new_name='deliverableName',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='duration_min',
            new_name='durationMin',
        ),
    ]
