# Generated by Django 6.0.6 on 2026-07-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_rename_deliverable_name_experience_deliverablename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencequestion',
            name='maxLength',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
