# Generated by Django 6.0.6 on 2026-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_experiencequestion_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencequestion',
            name='maxLength',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
