# Generated by Django 6.0.6 on 2026-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_experiencequestion_maxlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='reason',
        ),
        migrations.AddField(
            model_name='major',
            name='reason1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='major',
            name='reason2',
            field=models.TextField(blank=True),
        ),
    ]
