# Generated by Django 6.0.6 on 2026-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_remove_major_reason_major_reason1_major_reason2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='reason1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='major',
            name='reason2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
