# Generated by Django 6.0.6 on 2026-07-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='exploration_status',
            new_name='explorationStatus',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommendedMajor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendedAsFirst', to='search.major'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommendedMajor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendedAsSecond', to='search.major'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selectedMajor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selectedUsers', to='search.major'),
        ),
    ]
