# Generated by Django 6.0.6 on 2026-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_exploration_status_userprofile_explorationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exploration_status',
            field=models.CharField(choices=[('survey', 'Survey'), ('exploring', 'Exploring'), ('selected', 'Selected')], default='survey', max_length=20),
        ),
    ]
