# Generated by Django 6.0.6 on 2026-07-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_exploration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='exploration_status',
        ),
    ]
