# Generated by Django 6.0.6 on 2026-07-14 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculums', '0002_remove_material_lessons_remove_material_majors_and_more'),
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('material_type', models.CharField(choices=[('lecture', '강의'), ('article', '아티클'), ('practice', '실습'), ('program', '프로그램'), ('book', '도서')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('duration_text', models.CharField(blank=True, max_length=30)),
                ('price_type', models.CharField(choices=[('free', '무료'), ('paid', '유료')], default='free', max_length=10)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('thumbnail_asset_key', models.CharField(blank=True, max_length=100)),
                ('recommendation_reason', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('last_checked_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('lessons', models.ManyToManyField(blank=True, related_name='materials', to='curriculums.lesson')),
                ('majors', models.ManyToManyField(blank=True, related_name='materials', to='search.major')),
                ('stages', models.ManyToManyField(blank=True, related_name='materials', to='curriculums.stage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='materials.material')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'material')},
            },
        ),
    ]
